### ISSUE TITLE
Data types and variables

### ISSUE THREAD

**Issue by SvetlanaM** [encukou/blog#1]
Differences between
alias - vytvorenie a = b
plytka kopia objektu - pracuje sa iba s odkazom na objekt, pri zmene sa zmeni aj povodny objekt a = b[:]
hlboka kopia objektu - vytvori sa v pameti novy objekt deepcopy. Pri zmene sa povodny nezmeni.

**Comment by encukou** [comment]
_Alias_ bych asi měl zahrnout do existujícího článku; kopie zní jako dobré téma na článek navíc

**Comment by SvetlanaM** [comment]
Oki to necham na vas :+1:  ale viem, ze ludia to nevedia a casto s tym maju problem, napriklad ked niekto vytvori zoznam
a = [1,2]
potom a priradi do b
b = a[:]
a napriklad zmeni hodnotu v b
b[1] = 3
tak ocakavaju vo vypise print a, b toto:
[1,2], [1,3] namiesto tohto:
[1,3], [1,3]
