### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by SvetlanaM** [encukou/blog#2]
Zoradeny zoznam (list) operácie pridávania, mazania, na začiatok, koniec alebo pred / za určitý prvok. Sú menitelné. Můžu mař rozličnú dlžku a můžu obsahovař polozky různych dátových typov.
Zásobník (LIFO = Last In First Out = v Pythone sa s nimi pracuje pomocou zoznamou. Pridávanie nových prvkov pomocou append. výber prvku pomocou metódy pop() - vyberie vrchny prvok alebo pomocou metody pop(i) vyberie ity prvok. Su menitelne.
Fronta (FIFO - First In First Out) - implementovane v pytone pomocou zoznamu, aj ked to nie je velmi efektivne. Pracuje sa s nimi pomocou collections. Operacie pridavavania prvkov, mazania, a test prazdnosti fronty.
Ntica - je rovnaka ako zoznam. Namiesto hranatych zatvoriek obsahuje kulate a je nemenitelnou datovou strukturou. 
Mnoziny - obsahuju polozky bez duplicit. Zoznam mozeme konvertovat na mnozinu pomocou prikazu set.

**Comment by encukou** [comment]
Velice dobré téma, ale do aktuální série na jména/hodnoty/jmenné prostory se moc nehodí.

**Comment by SvetlanaM** [comment]
To uznavam ze nie, mozno dakedy v buducnosti, alebo mozno az po tom ako budu poznat zaklady :)
