### ISSUE TITLE
Dynamicke implicitne typovanie

### ISSUE THREAD

**Issue by SvetlanaM** [encukou/blog#3]
Narozdiel od statickeho sa v Pythone datovy typ nedefinuje. Pri deklaracii premennej sa urci sam automaticky. Pocas prace sa moze zmenit. 

Osetrenie pomocou exceptions napriklad. Kod doplnim potom .

**Comment by encukou** [comment]
Přijde mi že rozdíl mezi statickým a dynamickým typováním by ocenili spíš lidi co už znají jiný jazyk jako C nebo Javu; já teď píšu pro začátečníky obecně které by to myslím jen zmátlo.

Výjimky přijdou časem na řadu, ale to bych radši dal do praktičtějšího tutoriálu. Ještě před to co mám na blogu teď by to chtělo nějaké základní programy s if, for, import; výjimky bych probral až po tom co mám teď v "osnově".

**Comment by encukou** [comment]
Takže – jestli chceš napsat něco ty, tohle je dobré téma. Já se k tomu dostanu až za dlouho.

**Comment by SvetlanaM** [comment]
Jasne napisem, ale mozem to pisat v ramci vasho blogu alebo si mam zalozit vlastny?

**Comment by SvetlanaM** [comment]
hm...no teraz ma napadlo, ze tie importy a zakladne ify a to je super. To k importom mozem napisat aj ja aky je medzi nimi rozdiel
import kniznica - nacita celu knihovnu a nasledne volanie bude kniznica.funkcia()
import kniznica as nazov
from kniznica import funkcia - volanie bude potom iba .funkcia()
from kniznica import \* - ale to sa vraj neodporuca pouzivat

**Comment by encukou** [comment]
Vlastní blog je asi lepší. 
FWIW, můj blog začal jako gitovský repozitář s pár Markdown soubory co se daly číst na Githubu; až pak jsem dodělal všechno okolo. Takže stačí Git repozitář se souborem `posts/2014-01-08-nazev-clanku.md` :)

Uchytí-li se to, můžem to pak nějak spojit, udělat design, koupit doménu, vydat knižně, atd... Ale hlavní je obsah :)

Jo a doporučuju CC licenci (viz můj blog), ať se s tím pak dá pracovat.

**Comment by SvetlanaM** [comment]
Oki tak ja zacnem s vlastnym ale tak aspon sa dohodnime aby sme nepisali duplicitne tie veci aj ked ja by som radsej pisala pre tych co uz vedia Python a zacinaju s Djangom zase a ako ho spustit na Heroku a vsetko okolo toho, co ty na to? Potom v dalekej dalekej buducnosti , lebo mne vsetko trva dlho :D by sme tie clanky mohli spojit

**Comment by encukou** [comment]
Fajn, budu se těšit. Spojit to můžem, ale k takovýmhle webovým věcem se já asi nedostanu nikdy :)

**Comment by SvetlanaM** [comment]
Neboj, ja sa budem vela ucit aj z tvojho webu, velmi vela :+1:
