### ISSUE TITLE
Missing HTTP->HTTPS redirects

### ISSUE THREAD

**Issue by webknjaz** [encukou/blog#6]
Hi, I noticed that your Twitter profile links http://encukou.cz/ and when clicked, browsers show the broken lock icon. Turns out, GitHub Pages don't redirect to HTTPS for you. Sometimes, the related setup just gets broken on the GH side over time. I think that turning
[x] Enforce HTTPS
off and on again should fix it.
The setting is here: https://github.com/encukou/blog/settings/pages.

**Comment by encukou** [comment]
Thanks, I updated the Twitter link.

But, I'll also need to set up or remember a HTTP-only site for when I'm stuck at some captive portal :)

**Comment by webknjaz** [comment]
Yeah, Hynek has a few of those @ https://hynek.me/til/beryl-ax-captive-portal/. Plus, there's http://neverssl.com.

**Comment by encukou** [comment]
Thanks for the tip! http://neverssl.com/ sounds reasonable.
I've read Hynek's post, but p.ox.cx is something I don't think I can remember ;)
